runtime: python27
api_version: 1
threadsafe: false

handlers:
 - url: /.*
   script: main.app

libraries:
 - name: ssl
   version: latest

skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?.*/RCS/.*$
 - ^(.*/)?\..*$
 - ^Makefile$
 - ^alertlib-src/.*$
 - ^python-slackclient-src/.*$
 - ^humanize-src/.*$
