runtime: python
vm: true
entrypoint: gunicorn -b :$PORT main:app

manual_scaling:
  instances: 1

skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?.*/RCS/.*$
 - ^(.*/)?\..*$
 - ^Makefile$
 - ^alertlib-src/.*$
 - ^python-slackclient-src/.*$
